spring:
  application:
    name: microservice-discovery-eureka

security:
  basic:
    enabled: false
  user:
    name: user
    password: password
---
spring:
  profiles: peer1

server:
  port: 8761

eureka:
  client:
    service-url:
      defaultZone: http://eureka2:8762/eureka/
---
spring:
  profiles: peer2

server:
  port: 8762

eureka:
  client:
    service-url:
      defaultZone: http://eureka1:8761/eureka/



#security:
#  basic:
#    enabled: false
#server:
#  port: 8761
#eureka:
#  client:
#    registerWithEureka: false
#    fetchRegistry: false
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/